var capitulo1 = "<div class='imagem1'> <img src='https://media.discordapp.net/attachments/1020361087956295701/1022220584559579147/cabana.jpg'> </div><br> <h2>Capítulo 1</h2> <p>Você foi passar férias em uma cidade pequena, e em um fim de tarde você decide fazer uma caminhada. Percebendo que a chuva se aproximava e a noite chegava, você vê a necessidade de procurar abrigo. Enquanto se dirigia por uma trilha em direção ao local que está hospedado ouve o som de uma pessoa gritando. Olhando mais a fundo você nota que esse som vem de uma casa pequena. Você nota a porta entreaberta, mas a casa não tem nenhum sinal de ter alguém dentro naquele momento. Então, você passa a considerar se deve ou não averiguar o local. <br><br> Nesse momento você deve escolher:<br><br>[1] Após pensar um pouco, você nota que talvez não seja uma boa ideia entrar nessa casa. Afinal de contas, você não sabe que tipo de pessoa vive lá. Você decide esquecer isso e apenas ir embora, já que a casa não parece um lugar seguro para se esconder.<br><br>[2] Você realiza que não seria ético ignorar uma pessoa gritando. Afinal, talvez alguém esteja precisando de ajuda. O mais certo é entrar e ver se está tudo bem. Assim, você vai sorrateiramente entrar na casa pra descobrir o que está acontecendo, afinal a chuva estava aumentando e você também precisava se esconder. </p> <button onclick='carregarConteudo(capitulo2)'>1</button> <button onclick='carregarConteudo(capitulo2a)'>2</button>";

var capitulo2 = "  <h2> Capítulo 2</h2><p>Após algum tempo analisando o cenário, você decide seguir seu rumo. Ainda atordoado com a cena, resolve entrar em um restaurante no meio do trajeto. A sensação de ser observado te incomoda enquanto você está sentado em uma das mesas, ainda que ele esteja quase vazio. Um homem de meia idade entra pela porta e você rapidamente dirige sua atenção a ele, percebendo uma longa barba grisalha e um olho cego. Ele se senta em uma mesa de costas para você, que continua o observando por algum tempo. Depois de se distrair, você lembra que precisa ir embora, e enquanto paga a conta percebe a figura misteriosa do funcionário, que sequer notaria sua presença enquanto você deixava o dinheiro no balcão</p> <button onclick='carregarConteudo(capitulo3)'>Continuar</button>";

var capitulo3 = "  <h2> Capítulo 3</h2>  <p>Saindo do restaurante, você começa a caminhar em direção a sua cabana. Você tenta andar rápido na chuva enquanto uma sensação estranha está no ar. Chegando em casa, você olha para o relógio e já são 19:30. Você se troca e toma um banho e se prepara para dormir, antes que você pudesse se deitar na cama um barulho chama sua atenção: alguém bate na sua porta. Repentinamente, o acontecimento de mais cedo se passa na sua cabeça. Voltando a realidade, você se dirige para atender. Abrindo a porta, você se depara com a figura de uma idosa, que prontamente se apresenta.<br><br>Meu nome é Kana, moro na casa ao lado. Gostaria de saber se você pode me dar uma porção de açúcar, já que o meu acabou.Olhando a doce senhora, você diz que vai verificar se tem o açúcar, embora já tenha certeza da resposta, você usa esse tempo pra ponderar sobre o que deve fazer.  Você percebe que não há razão para não lhe dar a porção de açúcar, já que a senhora parece ser uma pessoa amigável. Também é uma boa oportunidade de conhecer os vizinhos.</p><br> <button onclick='carregarConteudo(capitulo4)'>Continuar</button>";

var capitulo4 = " <h2> Capítulo 4</h2>  <p>Ainda meio paranoico com a situação, você decide fechar sua casa e dormir. Apesar de acordar algumas vezes durante a noite, você consegue dormir e quando acorda no outro dia percebe a janela aberta. Você se pega questionando nos primeiros momentos após acordar sobre isso, já que não tem a certeza se havia fechado aquela janela antes de dormir. Resolvendo deixar essa situação de lado, você come e se prepara para ir conhecer a cidade. Quando você cruza a porta quase que de forma imediata é interrompido por um homem que se move na sua direção.<br> Olá, meu nome é James. Você é novo aqui? Eu também vim só passar as férias, é minha primeira vez, vim do Texas. Estou indo a um restaurante aqui perto, você quer ir comigo? Nós devemos ser as únicas duas pessoas que não falamos japonês aqui.<br><br>Depois de passar por tudo isso, é bom encontrar um conterrâneo. Sem exitar você aceita o convite e segue em direção ao restaurante enquanto James te conta um pouco mais sobre sua vida nos Estados Unidos e sobre sobre o que veio fazer no Japão.Chegando no restaurante, vocês sentam para fazer um pedido de café da manhã, e antes que você pudesse começar a ler o cardápio em japonês, James já faz sua escolha e avisa a atendente. O sotaque de James, ou a falta dele, te chama a atenção. Não parecia o sotaque de alguém do Texas, mas relevando esse fato você decide fazer o mesmo pedido.</p>.<br> <button onclick='carregarConteudo(capitulo5)'>Continuar</button>";

var capitulo5 = " <h2>Capítulo 5</h2> <p>Logo após finalizar o café da manhã, olhando no relógio você percebe que já passava das 10:00. As horas passaram tão rápido e você nem havia percebido, então você resolver ir embora. Ao avisar James, ele prontamente se dispõe a te levar para casa, insistindo que é uma longa distância para andar a pé.<br> Convencido pela generosidade do mesmo você aceita a carona sem pensar muito, e assim segue rumo a sua casa.Ao chegar em casa, você segue determinado em direção ao guarda-roupa, já que você pretendia fazer uma trilha ainda nessa tarde. <br> Procurando em uma das gavetas você tenta achar o seu kit de sobrevivência na selva, e logo percebe a mochila vermelha. Entretanto, quando você a abre, sente a falta de algo. O seu canivete não estava ali, e você tinha plena certeza de o ter guardado.<br>Ainda sem entender, você sai do lado de casa. A primeira coisa a te chamar a atenção é a presença de Kana, a idosa de antes. Você se aproxima dela e inicia um diálogo, perguntando para a mesma se ela havia notado algo estranho na vizinhança naqueles dias, já que um pertence pessoal de valor havia sumido. A mesma diz não saber de nada, mas algo segue te incomodando. O vizinho James, que surgiu como uma figura de bondade tão repentinamente. <br><br>[1] Você resolve perguntar: Você já notou algo de estranho no rapaz que mora aqui do lado, James?<br><br>[2] Apesar da vontade de perguntar, você se contém. Pensando bem, ele parece ser um cara legal. Além do mais, você não quer criar uma confusão.</p> <button onclick='carregarConteudo(capitulo6)'>1</button> <button onclick='carregarConteudo(capitulo6a)'>2</button>";

var capitulo6 = "<h2> Capítulo 6</h2>  <p>Logo após perguntar isso, e antes que a senhora pudesse responder, você ouve passos se aproximando e rapidamente a figura de James se materializa. Num primeiro momento, a única coisa que passa pela sua cabeça é se o mesmo havia conseguido escutar o que você dizia sobre ele. E o assunto que ele conversara com a senhora não te ajudava em nada a compreender isso. Talvez ele tenha escutado e esteja fingindo? Ou ele estava longe demais para ter conseguido escutar? Você não vai saber se não perguntar, afinal de contas. Incomodado com isso, você resolve voltar pra sua casa, deixando James e Kana conversando. <br>Chegando em casa, você nota que faltava água. E como isso não pode esperar, você precisava se dirigir para um mercado para comprar água. Você pega as chaves do seu carro do lado da cama e vai em direção ao mercado. Antes de cruzar a porta dupla do mercado, alguém falando alto te chama a atenção. Você, disperso, não havia percebido antes, mas ele falava com você. Era um idoso, o mesmo que você havia visto no bar antes, fácilmente reconhecido pela barba grisalha e um olho sem visão.<br>Tenha cuidado, os estranhos são perigosos aqui. Alguém próximo a mim desapareceu, e a polícia não quer fazer nada a respeito.<br>Apesar de revoltado, ele não parecia completamente louco. Enquanto entra no mercado e faz suas compras, você reflete sobre quão lúcido o idoso estava.</p>.<br> <button onclick='carregarConteudo(capitulo7)'>Continuar</button>";

var capitulo6a = "<h2> Capítulo 6</h2>  <p>Após resolver dissipar suas suspeitas acerca de James, você desiste da ideia de questionar a senhora a respeito do mesmo. E num piscar de olhos, você olha pra trás e percebe o mesmo se aproximando. Prontamente, ele inicia um diálogo sobre o clima. A senhora segue dialogando com vocês dois sobre como o dia estava agradável. Apesar da conversa estar legal, você resolve ir pra sua casa. O dia era longo e você ainda pretendia fazer várias coisas.<br>Chegando em casa, você nota que faltava água. E como isso não pode esperar, você precisava se dirigir para um mercado para comprar água. Você pega as chaves do seu carro do lado da cama e vai em direção ao mercado. Antes de cruzar a porta dupla do mercado, alguém falando alto te chama a atenção. Você, disperso, não havia percebido antes, mas ele falava com você. Era um idoso, o mesmo que você havia visto no bar antes, fácilmente reconhecido pela barba grisalha e um olho sem visão.<br>Tenha cuidado, os estranhos são perigosos aqui. Alguém próximo a mim desapareceu, e a polícia não quer fazer nada a respeito.<br>Apesar de revoltado, ele não parecia completamente louco. Enquanto entra no mercado e faz suas compras, você reflete sobre quão lúcido o idoso estava.</p>.<br> <button onclick='carregarConteudo(capitulo7)'>Continuar</button>";

var capitulo7 = "</div> <h2>Capítulo 7 </h2> <p>Após uma longa noite de sono, você acorda no outro dia com muito barulho do lado de fora de sua casa. Sua primeira reação é levantar da cama e ir em direção a rua, onde você se depara com a maior parte dos seus vizinhos, conversando alto e chocados. Ao se aproximar de algumas pessoas, você inevitavelmente consegue escutar um pouco dos rumores. Eles diziam que uma das vizinhas havia morrido, mas que ninguém sabia ao certo a causa até então.<br> Olhando isso mais adiante, você percebe que a casa de Kana estava interditada. Tendo em mente que ela morava sozinha, você supõe que tenha sido ela a vítima. Por mais que você não conhecesse ela tão bem assim, não muda o fato de que era uma senhora que não fazia mal a ninguém. <br>Entre tantas pessoas, ver o idoso que você havia visto no restaurante e no mercadinho chama sua atenção. Até por que essa era uma das primeiras vezes que você o veria durante o dia, e você passa a se perguntar o por quê de sua presença ali. Ele a conhecia? Ou só ouviu os rumores? <br>Enquanto um perito adentrava o local, você espia pelo vão da porta que rapidamente se fechara. Por mais que você não seja nenhum especialista, não parecia com uma cena de crime. Não soava como um lugar onde alguém lutou pela sua vida, mas sim como uma morte por causa natural, principalmente levando em conta que ela já era uma senhora de idade. <br>Enquanto você estava imerso na cena, uma pessoa se aproxima. Você consegue ouvir os passos dela mesmo em meio a diversas conversas</p><button onclick='carregarConteudo(capitulo8)'>Continuar</button>"; 

var capitulo8 = "</div> <h2>Capítulo 8</h2> <p>Rapidamente você percebe que era James, que chegava diretamente em você, com o propósito de falar sobre aquilo que acabava de acontecer. Apesar de não ser uma velha conhecida, não deixa de ser uma morte do lado da sua cabana. É algo no mínimo peculiar.<br> O que aconteceu aí?<br>Após sua breve explicação sobre o que você pode concluir naqueles 10 minutos, James te interrompe como quem sequer escutava o que você estava dizendo. Ele aponta na direção oposta da cabana, chamando sua atenção para o idoso do bar, que estava sozinho observando todo o ocorrido.<br>Você reparou naquele cara? Não é estranho pra você? Eu nunca o vi por aqui. Quer dizer, não nesse vilarejo. É estranho que esteja aqui justo hoje.<br>Você confirma, e agora que James mencionou, realmente é estranho. Não é a pessoa que você esperava ver, e você se questiona o fato de ele estar ali. Mas talvez, apenas talvez, antes de James falar você não tivesse dado tanta atenção a esse fato. É como se ele tivesse plantado a dúvida na sua cabeça.<br>Passado alguns dias, a morte continuava sem explicação. É fato que causas naturais é uma explicação mais plausível, e também é bem verdade que a polícia não iria se ocupar com a morte de uma idosa numa cidade pequena. Mas com o passar desse tempo, em um dos dias você nota uma movimentação na casa da idosa...</p><button onclick='carregarConteudo(capitulo9)'>Continuar</button>";

var capitulo9 = "</div> <h2>Capítulo 9</h2> <p>Sua curiosidade é mais forte e você vai ao lado de fora tentar entender o que acontecia ali. Na verdade, havia alguém na casa de Kana. Ele conversava com algumas pessoas e gesticulava na porta da casa, e honestamente, ele não parecia muito abalado com a morte. Mas talvez ele já imaginasse isso. <br>Passa pela sua cabeça a possibilidade de saber mais sobre o que aconteceu com a senhora conversando com aquele rapaz, mas você acaba decidindo não fazer. Talvez seja um momento difícil, de luto, e era melhor o deixar em paz.<br>Mas e se ele souber te dizer o que aconteceu? Nesse momento, você põe na balança se deve ou não fazer.<br><br>[1] Você resolve ir até ele perguntar sobre o que aconteceu com a senhora.<br>[2] Você resolve preservá-lo e não pergunta, ao invés disso, vai ocupar a mente fazendo outra coisa.</p><button onclick='carregarConteudo(capitulo10)'>1</button> <button onclick='carregarConteudo(capitulo10a)'>2</button>";

var capitulo10 = "</div> <h2>Capítulo 10</h2> <p>Você caminha até o rapaz na tentativa de obter respostas. Perguntando a ele o que aconteceu, ele te olha bem antes de esboçar uma resposta, e logo em seguida, começa a falar:<br></p><button onclick='carregarConteudo(capitulo11)'>Seguir</button>";

var capitulo10a = "</div> <h2>Capítulo 10</h2> <p></p><button onclick='carregarConteudo(capitulo11)'>Seguir</button>";

var capitulo11 = "</div> <h2>Capítulo 11</h2> <p></p><button onclick='carregarConteudo(capitulo12)'>Seguir</button>";

var capitulo = "</div> <h2>Capítulo 12</h2> <p></p><button onclick='carregarConteudo()'>Seguir</button>";



var final = " <h2>Obrigado por jogar</h2> <p>Agradecemos por jogar nosso jogo, ainda há mais finais para desbravar.</p><button onclick='carregarConteudo(inicioJornada)'>Continuar</button>";


var elemento = document.getElementById("conteudo");

function carregarConteudo(conteudo) {
    elemento.innerHTML = conteudo;
}

function modoEscuro() {
    var corpo = document.getElementById('corpo');
    var mudarBotao = document.getElementById('apagavel');
    corpo.classList.toggle('black');
    mudarBotao.classList.toggle('black-bnt');
}

function modobranco () {
    var corpo = document.getElementById('corpo');
    corpo.classList.remove('black');
}   

carregarConteudo(capitulo1);
